# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Vite CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-job:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g yarn
    - run: yarn install
    - run: yarn run build

  notification:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBED: ${{
            "username": "Webhook",
            "avatar_url": "https://i.imgur.com/4M34hi2.png",
            "content": "Text message. Up to 2000 characters.",
            "embeds": [
              {
                "author": {
                  "name": "Birdie♫",
                  "url": "https://www.reddit.com/r/cats/",
                  "icon_url": "https://i.imgur.com/R66g1Pe.jpg"
                },
                "title": "Title",
                "url": "https://google.com/",
                "description": "Text message. You can use Markdown here. *Italic* **bold** __underline__ ~~strikeout~~ [hyperlink](https://google.com) `code`",
                "color": 15258703,
                "fields": [
                  {
                    "name": "Text",
                    "value": "More text",
                    "inline": true
                  },
                  {
                    "name": "Even more text",
                    "value": "Yup",
                    "inline": true
                  },
                  {
                    "name": "Use `\"inline\": true` parameter, if you want to display fields in the same line.",
                    "value": "okay..."
                  },
                  {
                    "name": "Thanks!",
                    "value": "You're welcome :wink:"
                  }
                ],
                "thumbnail": {
                  "url": "https://upload.wikimedia.org/wikipedia/commons/3/38/4-Nature-Wallpapers-2014-1_ukaavUI.jpg"
                },
                "image": {
                  "url": "https://upload.wikimedia.org/wikipedia/commons/5/5a/A_picture_from_China_every_day_108.jpg"
                },
                "footer": {
                  "text": "Woah! So cool! :smirk:",
                  "icon_url": "https://i.imgur.com/fKL31aD.jpg"
                }
              }
            ] 
        }}
        uses: Ilshidur/action-discord@master
